# Generated by Django 5.1 on 2024-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
